---
- name: Deploy war file in tomcat
  hosts: client
  become: true
  vars_files:
  - nexus-cred.yml
  tasks:
    - name: Install lxml
      pip: 
       name: lxml
       
    - name: "Download war file"
      maven_artifact:
        group_id: websocket-demo
        artifact_id: websocket-demo
        version: 0.0.1-SNAPSHOT
        extension: war
        repository_url: "http://172.173.154.5:8081/repository/maven-snapshots"
        username: "{{ username }}"
        password: "{{ password }}"
        dest: "/opt/tomcat/webapps/spring-boot-chat-app.war"
        mode: '0644'

    - name: Enable the tomcat service and start     
      systemd:
        name: tomcat
        enabled: yes
        state: restarted
