---
- name: Install Tomcat to remote server
  hosts: all
  become: yes
  vars:
    download_url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
  tasks:
   - name: Update and upgrade apt packages
     apt:
      upgrade: yes
      update_cache: yes

   - name: Download Open JDK     
     apt:
      name: default-jdk
      update_cache: yes
      state: present
  
   - name: Check if Java is Installed
     shell: 
      java -version
     
   - name: Create Group     
     group: 
      name: tomcat
      state: present

   - name: Create User     
     user:
        name: tomcat
        state: present

   - name: Create a Directory /opt/tomcat     
     file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat

   - name: Download Tomcat using unarchive     
     unarchive:
      src: "{{download_url}}"
      dest: /opt/tomcat       
      remote_src: yes
      extra_opts: [--strip-components=1]
   - name: Change ownership of tomcat directory
     file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

   - name: Creating a service file     
     copy: 
      content: |-
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target

        [Service]
        Type=forking
        User=tomcat
        Group=tomcat

        Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
        Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
        Environment="CATALINA_PID=/opt/tomcat/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/tomcat"
        Environment="CATALINA_HOME=/opt/tomcat"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

        ExecStart=/opt/tomcat/bin/startup.sh
        ExecStop=/opt/tomcat/bin/shutdown.sh
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service

   - name: Reload the SystemD to re-read configurations     
     systemd:
        daemon-reload: yes

   - name: Enable the tomcat service and start     
     systemd:
        name: tomcat
        enabled: yes
        state: started

   - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
     tags: test
     uri:
       url: http://localhost:8080
     register: result
     until: "result.status == 200"
     retries: 5
     delay: 10



    

     