pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                git credentialsId: 'git-key', url: 'git@github.com:arnabcs10/springboot-chat-app.git'
            }
        }
        
        stage('Install Docker'){
            steps {
                ansiblePlaybook colorized: true, credentialsId: 'git-key', disableHostKeyChecking: true, inventory: 'ansible/dev.inv', playbook: 'ansible/docker-install.yaml'
            }
        }
        stage('Run Docker Image'){
            steps {
                ansiblePlaybook colorized: true, credentialsId: 'git-key', disableHostKeyChecking: true, inventory: 'ansible/dev.inv', playbook: 'ansible/deploy-docker-image.yaml', vaultCredentialsId: 'vault-pass'
            }
        }
    }
}
