---
- name: Install Apache Tomcat10 using ansible
  hosts: worker
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
 
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: Download Tomcat using unarchive
      become: yes
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /opt/tomcat8
        mode: 0755
        remote_src: yes
        group: tomcat
        owner: tomcat 
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory    
    - name: Creating a service file
      become: yes
      copy: 
       content: |-
         [Unit]
         Description=Tomcat Service
         Requires=network.target
         After=network.target
         [Service]
         Type=forking
         User=tomcat
         Environment="CATALINA_PID=/opt/tomcat8/logs/tomcat.pid"
         Environment="CATALINA_BASE=/opt/tomcat8"
         Environment="CATALINA_HOME=/opt/tomcat8"
         Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
         ExecStart=/opt/tomcat8/bin/startup.sh
         ExecStop=/opt/tomcat8/bin/shutdown.sh
         Restart=on-abnormal
         [Install]
         WantedBy=multi-user.target
       dest: /etc/systemd/system/tomcat.service
    
 
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
