---
- name: Install Tomcat to remote server
  hosts: all
  become: yes
  vars_files:
    - cred.yaml
  tasks:
   - name: Update and upgrade apt packages
     apt:
      upgrade: yes
      update_cache: yes

   - name: Install lxml
     pip:
      name: lxml

   - name: Download artifact from nexus private repository 
     maven_artifact:
      group_id: websocket-demo
      artifact_id: websocket-demo
      version: 0.0.1-SNAPSHOT
      repository_url: 'http://40.117.186.85:8081/repository/maven-snapshots'
      username: "{{ username }}"
      password: "{{ password }}"
      dest: /opt/tomcat/webapps/chatapp.war
      mode: "0644"

   - name: Restart Tomcat
     systemd:
      name: tomcat
      enabled: yes
      state: restarted