
---
- hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: ensure docker registry is available
      apt_repository: 
        repo: 'deb https://download.docker.com/linux/ubuntu bionic stable' 
        state: present

    - name: ensure docker and dependencies are installed
      apt: 
        name: docker-ce 
        update_cache: yes
    - name: install docker py
      pip:
              name: docker
    - name: ensure docker can use insecure registries in 10.0.0.0/24
      copy:
        content: |-
          {
            "insecure-registries" : ["172.174.114.128:8085"]
          }
        dest: /etc/docker/daemon.json
    - name: restart service docker
      service: 
        name: docker
        state: restarted