---
- name: Deploy jar artifact from nexus
  hosts: tomcat
  become: yes
  tasks:
    - name: install lxml
      ansible.builtin.apt:
        name: python3-lxml
        update_cache: yes
    - name: "Download war file"
      maven_artifact:
        group_id: websocket-demo
        artifact_id: websocket-demo
        version: 0.0.1-SNAPSHOT
        extension: war
        repository_url: "http://4.227.129.1:8081/repository/maven-snapshots"
        username: "admin"
        password: "admin"
        dest: "/opt/tomcat/webapps/spring-boot-chat-app.war"
        mode: "0644"
