---
- name: Deploy and start Tomcat on worker node
  hosts: tomcat
  become: yes
  tasks:
  - name : adding a new user
    ansible.builtin.user:
      name: tomcat
 
  - name: create a Tomcat Group
    group:
      name: tomcat

  - name: Update the worker nodes
    apt: 
      update_cache=yes 

  - name: Install default-jdk
    apt:
      name: default-jdk
      state: present


  - name: create directory
    ansible.builtin.file:
      path: /opt/tomcat/
      state: directory
      mode: '0755'
  - name: download & untar the package
    ansible.builtin.unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
      dest: /opt/tomcat/
      remote_src: yes
      extra_opts: [--strip-components=1]
  - name: Change ownership of tomcat directory
    file:
      path: /opt/tomcat/
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  - name: copy the tomcat.service file
    copy:
      src: ./files/tomcat.service
      dest: /etc/systemd/system/
      mode: 0755

  - name: Start and enable tomcat
    systemd:
      name: tomcat
      state: started
      daemon_reload: true


