---
- name: Deploy Docker Image
  hosts: all
  become: true
  vars_files:
    - cred.yaml
  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:        
        username: "{{ username }}"
        password: "{{ password }}"
        reauthorize: yes
        
    - name: Running Docker Conatiner
      docker_container:        
        name: chatapp
        image: arnabcs10/container-node-project:latest
        state: started
        pull: yes
        ports:
        - "3000:3000"
    - name: Connect to app server on port 3000 and check status 200 - Try 5 times
      tags: test
      uri:
        url: http://localhost:3000
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 10
    
