apiVersion: v1
kind: Service
metadata:
  name: node-backend-lb
  # namespace: development
spec:
  type: LoadBalancer
  selector:
    app: node-backend
  ports:
    - port: 3001
      targetPort: 3001
