---
- hosts: ubuntu
  become: true
  tasks:
    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: ensure docker registry is available
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

    - name: ensure docker and dependencies are installed
      apt: name=docker-ce update_cache=yes

    # - name: ensure docker can use insecure registries in nexus artifact registry
    #   lineinfile:
    #     path: /etc/docker/daemon.json
    #     line: { "insecure-registries": ["4.227.129.1:8085"] }
    #     create: yes

    - name: restart docker
      service: name=docker state=restarted
