pipeline {
    agent any
    stages {
        stage('pull the code') {
            steps {
               git branch: 'main', url: 'https://github.com/rohan0103/capstone-terraform.git'
            }
        }
        stage('Terraform version check') {
            steps {
                sh "terraform -v"
            }
        }
        stage('Initialize terraform') {
            steps {
                sh "terraform init"
            }
        }
        stage('Plan') {
            steps {
                sh "terraform plan"
            }
        }
        stage('Deploy the resoources') {
            steps {
                sh '''
                    VM_IP=$(terraform apply -auto-approve | grep "vm_ip"); echo $VM_IP >> IP.txt;
                '''
            }
        }
        stage('SSH the machine') {
            steps {
                sh ''' 
                ex_ip=$(grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" IP.txt >> result.txt)
                    export EX_IP=$(cat result.txt)
                    ssh -i  /var/lib/jenkins/.ssh/id_rsa  -o StrictHostKeyChecking=no adminuser@$EX_IP < command.txt
                  '''
            }
        }
        
    }
}