pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                git credentialsId: 'git-key', url: 'git@github.com:arnabcs10/springboot-chat-app.git'
            }
        }
        
        stage('Install Tomcat'){
            steps {
                ansiblePlaybook colorized: true, credentialsId: 'git-key', disableHostKeyChecking: true, inventory: 'ansible/dev.inv', playbook: 'ansible/tomcat.yaml'
            }
        }

        stage('Deploy WAR File'){
            steps {
                ansiblePlaybook colorized: true, credentialsId: 'git-key', disableHostKeyChecking: true, inventory: 'ansible/dev.inv', playbook: 'ansible/deploy-war-file.yaml', vaultCredentialsId: 'vault-pass'
            }
        }
        
    }
}
