---
- name: Deploy Docker Image
  hosts: all
  become: true
  vars_files:
    - cred.yaml
  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: 40.117.186.85:8085
        username: "{{ username }}"
        password: "{{ password }}"
        reauthorize: yes
        
    - name: Running Docker Conatiner
      docker_container:        
        name: chatapp
        image: 40.117.186.85:8085/chatapp        
        state: started
        pull: yes
        ports:
        - "8081:8081"
    - name: Connect to app server on port 8080 and check status 200 - Try 5 times
      tags: test
      uri:
        url: http://localhost:8081
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 10
    
