---
- name: Install Tomcat to remote server
  hosts: all
  become: yes  
  vars:
    download_url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
  tasks:
   - name: Update and upgrade apt packages
     apt:
      upgrade: yes
      update_cache: yes

   - name: Download Open JDK     
     apt:
      name: default-jdk
      update_cache: yes
      state: present
  
   - name: Check if Java is Installed
     shell: 
      java -version
     
   - name: Create Group     
     group: 
      name: tomcat
      state: present

   - name: Create User     
     user:
        name: tomcat
        state: present

   - name: Create a Directory /opt/tomcat     
     file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat

   - name: Download Tomcat using unarchive     
     unarchive:
      src: "{{download_url}}"
      dest: /opt/tomcat       
      remote_src: yes
      extra_opts: [--strip-components=1]
   - name: Change ownership of tomcat directory
     file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

   - name: Creating a service file     
     copy: 
      src: templates/tomcat.service.j2        
      dest: /etc/systemd/system/tomcat.service

   - name: Reload the SystemD to re-read configurations     
     systemd:
        daemon-reload: yes

   - name: Enable the tomcat service and start     
     systemd:
        name: tomcat
        enabled: yes
        state: started

   - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
     tags: test
     uri:
       url: http://localhost:8080
     register: result
     until: "result.status == 200"
     retries: 5
     delay: 10