---
- name: Deploying docker image
  hosts: all
  become: true
  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: 52.147.200.247:8085
        username: admin
        password: admin@123
        reauthorize: yes
    - name: excuting the container
      docker_container:
        name: chatapp
        image: 52.147.200.247:8085/chatapp
        state: started
        pull: 'true'
        ports:
          - "8081:8080"
    - name: Connect to Tomcat server on port 8080
      tags: test
      uri:
        url: http://localhost:8080
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 10
